---
title: "figs"
author: "Diamantis Sellis"
date: "November 2, 2017"
output: 
  html_document: default
  code_folding: hide
  self_contained: no
  clean: false
---

<!--
Rscript -e 'library(rmarkdown); rmarkdown::render("figs.Rmd", "html_document")'
-->

```{r, loadLibraries}
library(tidyverse)
library(latex2exp)
library(cowplot)
source("~/Dropbox/transientDynamics/analysis/funcs.R")
theme_set(theme_classic())
```

```{r, loadData}
gradientV <- read.table("~/Dropbox/transientDynamics/data/gradient.vector.dat", stringsAsFactors = FALSE)
gradientS <- read_delim("~/Dropbox/transientDynamics/data/gradient.statistics.dat", delim = "\t")
gradientW <- read.table("~/Dropbox/transientDynamics/data/gradient.window.dat", stringsAsFactors = FALSE, header = TRUE)

uniformV <- read.table("~/Dropbox/transientDynamics/data/uniform.vector.dat", stringsAsFactors = FALSE)
uniformS <- read_delim("~/Dropbox/transientDynamics/data/uniform.statistics.dat", delim = "\t")
uniformW <- read.table("~/Dropbox/transientDynamics/data/uniform.window.dat", stringsAsFactors = FALSE, header = TRUE)

gfeV<-read.table("~/Dropbox/transientDynamics/data/gfe.vector.dat", stringsAsFactors = FALSE)
golV<-read.table("~/Dropbox/transientDynamics/data/gol.vector.dat", stringsAsFactors = FALSE)

gfeF <- read.table("~/Dropbox/transientDynamics/data/gfe100.window.dat", stringsAsFactors = FALSE, header = TRUE)
golF<-read.table("~/Dropbox/transientDynamics/data/gol100.window.dat", stringsAsFactors = FALSE, header = TRUE)

gfeW <- read.table("~/Dropbox/transientDynamics/data/gfe.window.dat", stringsAsFactors = FALSE, header = TRUE)
golW <- read.table("~/Dropbox/transientDynamics/data/gol.window.dat", stringsAsFactors = FALSE, header = TRUE)

gfeS <- read.table("~/Dropbox/transientDynamics/data/gfe.statistics.dat", stringsAsFactors = FALSE, header = TRUE)
golS <- read.table("~/Dropbox/transientDynamics/data/gol.statistics.dat", stringsAsFactors = FALSE, header = TRUE)

gfesp <- read_tsv("~/Dropbox/transientDynamics/data/gfe100.statistics.dat")
golsp <- read_tsv("~/Dropbox/transientDynamics/data/gol100.statistics.dat")

```

```{r, gradients}
p1 <- (uniformW %>% 
  bind_rows(gradientW) %>% 
  filter(window == 1) %>% 
  ggplot(aes(x = replicate, y = K)) + geom_bar(stat ='identity'))

p2 <- (uniformW %>% 
  bind_rows(gradientW) %>% 
  filter(window == 1) %>% 
  ggplot(aes(x = replicate, y = H)) + geom_bar(stat ='identity'))
l <- 10
drawPlots <- FALSE
df <- data.frame(Dimension = numeric(l),
                 Pvalue    = numeric(l),
                 r2        = numeric(l))

for(i in c(0:8)){
  df[i+1,] <- plotScalc(uniformW[uniformW$replicate == i,], drawPlot = drawPlots)
}
df[10,] <- plotScalc(gradientW, drawPlot = drawPlots)
df$Label <- c("10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "gradient")
p3 <- (df %>% 
  ggplot(aes(x = Label, y = Dimension)) + geom_bar(stat = 'identity'))

gradient <- plot_grid(p1, p2, p3, labels = c("A", "B", "C"), ncol = 1, align = "v")
save_plot(png("../ms/figs/figureGradient.png",
          gradient,
          base_aspect_ratio = 1.7))

```

```{r, transformData}
# descriptive statistics
gfe <- evolutionStats(gfeF)
gol <- evolutionStats(golF)

# summary statistics by generation
gfestats <- (group_by(gfesp, generation) %>%
  summarise(mtl = mean(Ktl, na.rm = TRUE), q1tl = quantile(Ktl, 0.25, na.rm = TRUE), q2tl = quantile(Ktl, 0.75, na.rm = TRUE), 
            mce = mean(Kce, na.rm = TRUE), q1ce = quantile(Kce, 0.25, na.rm = TRUE), q2ce = quantile(Kce, 0.75, na.rm = TRUE)))
golstats <- (group_by(golsp, generation) %>%
  summarise(mtl = mean(Ktl, na.rm = TRUE), q1tl = quantile(Ktl, 0.25, na.rm = TRUE), q2tl = quantile(Ktl, 0.75, na.rm = TRUE), 
            mce = mean(Kce, na.rm = TRUE), q1ce = quantile(Kce, 0.25, na.rm = TRUE), q2ce = quantile(Kce, 0.75, na.rm = TRUE)))

# statistics on coarse grained grid
gfecgstats <- (gfeF %>% filter(window == 4) %>% group_by(replicate, generation, window) %>% 
        summarize(K1mean = mean(K,na.rm. = TRUE), Hmean = mean(H, na.rm = TRUE)))
golcgstats <- (golF %>% filter(window == 4) %>% group_by(replicate, generation, window) %>% 
        summarize(K1mean = mean(K,na.rm. = TRUE), Hmean = mean(H, na.rm = TRUE)))
```

```{r, timeEvolution, fig.cap = "Figure 1", fig.width = 3, fig.height = 9}
png("../ms/figs/figure1.png", width = 3, height = 9, units = "in", res = 300)
layout(matrix(c(1:3),ncol=1))
par(mai=c(0.1,0.1,0.1,0.1))
side <- 64

maxDensity <- max(gfeV[,2:ncol(gfeV)]) #largest overlap of particles
gc <- c("grey90",rev(grey.colors(maxDensity, start = 0, end = 0.5)))
for(i in c(0, 100000, 1000000)){
  plotState(gfeV, side = side, t = i, col = gc)
}
dev.off()
```

```{r, timeEvolutionS, fig.cap = "Figure S1", fig.width = 6, fig.height = 6}
png("../ms/figs/figureS1.png", width = 6, height = 6, units = "in", res = 300)
layout(matrix(c(1:6),ncol=2))
par(mai=c(0.1,0.1,0.1,0.1))
side <- 64

maxDensity <- max(gfeV[,2:ncol(gfeV)]) #largest overlap of particles
gc <- c("grey90",rev(grey.colors(maxDensity, start = 0, end = 0.5)))
for(i in c(0, 100000, 1000000)){
  plotState(gfeV, side = side, t = i, col = gc)
}

for(i in c(0, 100, 500)){
  plotState(golV, side = side, t = i, col = c("grey90", 1))
}
dev.off()
```

```{r, complexityFluctuations, fig.cap = "Figure 2"}
png("../ms/figs/figure2.png")
#tidy up tables
a <- filter(gfeW, window == 1)
b <- transmute(gfeS, generation,  Kratio = Ktl/Kce)
j <- left_join(a, b, by = "generation")
df <- gather(j, "Measure", "Complexity", K, Kratio)
ggplot(df, aes(x = generation, y = Complexity)) + geom_line() + facet_grid(Measure~.) + facet_grid(Measure ~ ., scales = "free_y") + geom_hline(data=data.frame(xint=1,Measure="Kratio"),aes(yintercept=xint),linetype="dotted")
dev.off()
df %>% mutate(nextRow = lag(Complexity),
              DK = Complexity - nextRow
              ) %>% 
  ggplot(aes(x=generation, y = DK)) + geom_bar(stat = 'identity')
```

```{r, complexityFluctuationsSGol, fig.cap = "Figure S3"}
png("../ms/figs/figureS3.png")
a <- filter(golW, window == 1)
b <- transmute(golS,generation,  Kratio = Ktl/Kce)
j <- left_join(a, b, by = "generation")
df <- gather(j, "Measure", "Complexity", K, Kratio)
ggplot(df, aes(x = generation, y = Complexity)) + geom_line() + facet_grid(Measure~.) + facet_grid(Measure ~ ., scales = "free_y") + geom_hline(data=data.frame(xint=1,Measure="Kratio"),aes(yintercept=xint),linetype="dotted")
dev.off()
```

```{r, subregionsgfe, fig.cap = "Figure 3"}
png("../ms/figs/figure3.png")
gfestats %>% ggplot(aes(x = generation)) + geom_ribbon(aes(x = generation, ymin = q1tl, ymax = q2tl), fill = "grey70", alpha = 0.5)  +  geom_line(aes(y = mtl), color ="red") + geom_ribbon(aes(x = generation, ymin = q1ce, ymax = q2ce), fill = "grey70", alpha = 0.5) + geom_line(aes(y = mce), color = "blue") + labs(y = "Kolmogorov complexity")
dev.off()
```

```{r, subregionstransientDynamics, fig.cap = "Figure S5"}
png("../ms/figs/figureS5.png")
golstats %>% ggplot(aes(x = generation)) + geom_ribbon(aes(x = generation, ymin = q1tl, ymax = q2tl), fill = "grey70", alpha = 0.5)  +  geom_line(aes(y = mtl), color ="red") + geom_ribbon(aes(x = generation, ymin = q1ce, ymax = q2ce), fill = "grey70", alpha = 0.5) + geom_line(aes(y = mce), color = "blue") + labs(y = "Kolmogorov complexity")
dev.off()
```

```{r, coarseGrainedStatsGFEab, fig.cap = "Figure 4ab"}
png("../ms/figs/figure4ab.png", width = 7, height = 5, units = "in", res = 300)

df <- gather(gfecgstats, "Measure", "Statistic", K1mean, Hmean)
df$Measure[df$Measure=="K1mean"] = "Kolmogorov Komplexity"
df$Measure[df$Measure=="Hmean"] = "Information entropy"
df %>%
  group_by(generation, Measure) %>% summarise(mean = mean(Statistic), sd = sd(Statistic)) %>% 
  mutate(sdmin = mean-sd, sdmax = mean+sd) %>% ggplot(aes(x = generation, y = mean)) + geom_ribbon(aes(ymin = sdmin, ymax = sdmax), fill = "grey70", alpha = 0.5) + geom_line() + facet_grid(Measure ~ ., scales = "free_y")
dev.off()
```

```{r, coarseGrainedStatsGFEc, fig.cap = "Figure4c"}
png("../ms/figs/figure4c.png", width = 7, height = 2.5, units = "in", res = 300)

gfeP <- plotSTcalc(gfeF)
par(las = 1, bty="u", mai = c(1.02, 0.82, 0, 0.42))
plot(gfeP$generations, gfeP$D,type="l",log="",ylab="", xlab="time")
points(gfeP$generations, gfeP$D + gfeP$DSE,type="l",lty=3)
points(gfeP$generations, gfeP$D - gfeP$DSE,type="l",lty=3)
par(new=TRUE)
plot(gfeP$generations, gfeP$Dr2,type="l",axes=FALSE,log="",xlab="",ylab="",col="red")
axis(4,ylim=c(0,99,1),col="red")
mtext("S",side=2,line=3)
mtext(expression(r^2),side=4,line=3)
par(new=FALSE)
dev.off()
```

```{r, coarseGrainedStatsGOLab, fig.cap = "Figure S6ab"}
png("../ms/figs/figureS6ab.png", width = 7, height = 5, units = "in", res = 300)

df <- gather(golcgstats, "Measure", "Statistic", K1mean, Hmean)
df$Measure[df$Measure=="K1mean"] = "Kolmogorov Komplexity"
df$Measure[df$Measure=="Hmean"] = "Information entropy"
df %>%
  group_by(generation, Measure) %>% summarise(mean = mean(Statistic), sd = sd(Statistic)) %>% 
  mutate(sdmin = mean-sd, sdmax = mean+sd) %>% ggplot(aes(x = generation, y = mean)) + geom_ribbon(aes(ymin = sdmin, ymax = sdmax), fill = "grey70", alpha = 0.5) + geom_line() + facet_grid(Measure ~ ., scales = "free_y")
dev.off()
```

```{r, coarseGrainedStatsGOLc, fig.cap = "Figure S6c"}
png("../ms/figs/figureS6c.png", width = 7, height = 2.5, units = "in", res = 300)
par(las = 1, bty="u", mai = c(1.02, 0.82, 0, 0.42))
golP <- plotSTcalc(golF)
par(bty="u")
plot(golP$generations, golP$D,type="l",log="",ylab="", xlab="time")
points(golP$generations, golP$D+golP$DSE,type="l",lty=3)
points(golP$generations, golP$D-golP$DSE,type="l",lty=3)
par(new=TRUE)
plot(golP$generations, golP$Dr2,type="l",axes=FALSE,log="",xlab="",ylab="",col="red")
axis(4,ylim=c(0,99,1),col="red")
mtext("S",side=2,line=3)
mtext(expression(r^2),side=4,line=3)
par(new=FALSE)
dev.off()
```

```{r, coarseGrainedStatstransientDynamicsab, fig.cap = "Figure 5ab"}
png("../ms/figs/figure5ab.png", width = 7, height = 5, units = "in", res = 300)

df <- (golcgstats %>% 
       filter(generation <= 50) %>% 
       gather("Measure", "Statistic", K1mean, Hmean))
df$Measure[df$Measure=="K1mean"] = "Kolmogorov Komplexity"
df$Measure[df$Measure=="Hmean"] = "Information entropy"
df %>%
  group_by(generation, Measure) %>% summarise(mean = mean(Statistic), sd = sd(Statistic)) %>% 
  mutate(sdmin = mean-sd, sdmax = mean+sd) %>% ggplot(aes(x = generation, y = mean)) + geom_ribbon(aes(ymin = sdmin, ymax = sdmax), fill = "grey70", alpha = 0.5) + geom_line() + facet_grid(Measure ~ ., scales = "free_y")
dev.off()
```

```{r, coarseGrainedStatsGolc, fig.cap = "Figure5c"}
golP <- plotSTcalc(golF)
png("../ms/figs/figure5c.png", width = 7, height = 2.5, units = "in", res = 300)
par(las = 1, bty="u", mai = c(1.02, 0.82, 0, 0.42))
plot(golP$generations, golP$D,type="l",log="",ylab="", xlab="time", xlim = c(0,50))
points(golP$generations, golP$D + golP$DSE, type="l", lty=3)
points(golP$generations, golP$D - golP$DSE, type="l", lty=3)
par(new=TRUE)
plot(golP$generations, golP$Dr2, type="l", axes = FALSE, log = "", xlab = "", ylab = "", col = "red")
axis(4,ylim=c(0,99,1),col="red")
mtext("S",side=2,line=3)
mtext(expression(r^2),side=4,line=3)
par(new=FALSE)
dev.off()
```

```{bash}
convert -append ../ms/figs/figure4ab.png ../ms/figs/figure4c.png ../ms/figs/figure4.png
convert -append ../ms/figs/figure5ab.png ../ms/figs/figure5c.png ../ms/figs/figure5.png
convert -append ../ms/figs/figureS6ab.png ../ms/figs/figureS6c.png ../ms/figs/figureS6.png
```